LLVM_INSTALL_PATH := /cs/cs70/llvm-2019/install
LLVM_LIB_PATH := $(LLVM_INSTALL_PATH)/lib
#LLVM_INSTALL_PATH = /usr/lib/llvm/6
#LLVM_LIB_PATH := $(LLVM_INSTALL_PATH)/lib64
LLVM_LDFLAGS :=  -Wl,-rpath,$(LLVM_LIB_PATH)
