test:
	../replacer -f "IntList::insert_after(IntList::Iterator, int)" -f "IntList::IntList()" -f "IntList::size()" cs70-intlist-bad1.cpp  cs70-intlist-good.cpp -- clang++ -isystem/Users/stone/llvm-install/lib/clang/3.6.0/include -isystem/usr/include/c++/4.2.1 -std=c++11 -c

test2:
	../replacer bigint-solution/bigint.cpp bigint-submission/bigint.cpp  -- clang++ -isystem/Users/stone/llvm-install/lib/clang/3.6.0/include -isystem/usr/include/c++/4.2.1 -std=c++11 -c

